version: "3.9"

services:
  frontend-prod:
    build:
      context: ./front
      dockerfile: Dockerfile.prod.yml
    ports:
      - "80:80"
    networks:
      - local
    restart: unless-stopped
    depends_on:
      - backend
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.yml
    ports:
      - "5173:5173"
    networks:
      - local
    depends_on:
      - backend
    volumes:
      - ./front:/app
      - /app/node_modules
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.yml
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - local
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000;

networks:
  local:
    driver: bridge
