version: "3.9"

services:
  frontend-prod:
    build:
      context: ./front
      dockerfile: Dockerfile.prod.yml
    ports:
      - "80:80"
      - "443:443"
    networks:
      - local
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.yml
    ports:
      - "5173:5173"
    networks:
      - local
    depends_on:
      - backend
    volumes:
      - ./front:/app
      - /app/node_modules
  backend:
    build:
      context: ./back
      dockerfile: Dockerfile.yml
    ports:
      - "5000:5000"
    restart: unless-stopped
    networks:
      - local
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT:-Production}
      - ASPNETCORE_URLS=http://+:5000;
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}
      - Jwt__Secret=${JWT_SECRET}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=sports_tracker_backend
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=docker
    depends_on:
      - db
      - otel-collector
  db:
    image: postgres:18
    networks:
      - local
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql
    ports:
      - 127.0.0.1:5433:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: ["--config=/etc/otel/config.yml"]
    networks:
      - local
    volumes:
      - ./collector-config.yml:/etc/otel/config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    networks:
      - local
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports: 
      - "9090:9090"

  loki:
    image: grafana/loki:latest
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - local
    ports: 
      - "3100:3100"

  grafana:
    image: grafana/grafana:latest
    networks:
      - local
    ports: 
      - "3200:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - loki
      - prometheus

networks:
  local:
    driver: bridge

volumes:
  db_data:
  grafana_data:
  prometheus_data: