{
 "title": "Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Gc collections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(sports_tracker_process_runtime_dotnet_gc_collections_count_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dotnet mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sports_tracker_process_runtime_dotnet_gc_allocations_size_bytes_total / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "500 errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(sports_tracker_http_server_request_duration_seconds_count{\n  http_response_status_code=~\"5..\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p99 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n  rate(sports_tracker_http_server_request_duration_seconds_bucket[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(sports_tracker_http_server_request_duration_seconds_count[5m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}